version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:latest
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD:

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: cd assets && npm install && node node_modules/brunch/bin/brunch build
      - run: mix ecto.create
      - run: mix phx.server
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix test
      - store_test_results:
          path: _build/test/lib/circle_ci_test
